"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import ez_setup
ez_setup.use_setuptools()

import sys
from setuptools import setup

APP = ['run.py']
OTPIONS = {
    "includes":
}

if sys.platform == 'darwin':
    OPTIONS["setup_requires"] = ["py2app"]
    OPTIONS["app"] = APP,
    extra_options = dict(
        setup_requires=['py2app'],
        app=APP,
        options=dict(py2app=dict(argv_emulation=True)),
    )
elif sys.platform == 'win32':
    extra_options = dict(
        setup_requires=['py2exe'],
        app=APP,
    )
else:
    extra_options = dict(
        scripts=APP)

setup(
    name="Souma",
    **extra_options
)
