""" Empty initial migration

Revision ID: 4e44fd06a62b
Revises: None
Create Date: 2014-05-09 00:47:22.477703

"""

# revision identifiers, used by Alembic.
revision = '4e44fd06a62b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
